apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-auth
data:
  AZP_TOKEN: 'NnN0dGFybHpvaWtqZnIyeWNhZGcyNHpxdGRnbDJob2M1bmZzbGlkcDUydTM0b2pmNmw2cQ=='
  AZP_URL: 'aHR0cHM6Ly9kZXYuYXp1cmUuY29tL2Z1cmthbmFrZ3VuODE='